version: "3"
services:
  db:
    image: "postgres:14-alpine"
    container_name: "postgres14"
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "root"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: